Repository position-pal/scala-template, pull requests merged in 2024-12, with the labels that each got.

#69 ci: docker and template updater
  .github/workflows/docker.yml
  .github/workflows/release.yml
  .github/workflows/template-sync.yml
  .templatesyncignore
  Dockerfile
  README.md
Labels: enhancement, squash

#79 ci: aggregate delivery-related jobs in a single workflow file and scaladoc generation
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/docker.yml
  .github/workflows/release.yml
  .github/workflows/template-sync.yml
  build.gradle.kts
  core/build.gradle.kts
  core/src/main/scala/io/github/positionpal/Launcher.scala
  core/src/main/scala/io/github/positionpal/Main.scala
  gradle/libs.versions.toml
  release.config.js
Labels: squash

#81 ci: fix cron job to run daily at 00:00 instead of at 00:00 on day-of-month 1
  .github/workflows/template-sync.yml
Labels: rebase

#91 ci!: checkout tags in scaladoc stage and use position-pal bot token release
  .github/workflows/cd.yml
Labels: squash
